github_username     = "your-github-username"
ghcr_pat            = "your-ghcr-personal-access-token"
github_email        = "your-email@example.com"
postgresql_admin_user = "admin_user"
postgresql_admin_password = "your-postgresql-password"
